let products = [
  {
    id: 1,
    model: "Les Paul Standard '50s",
    type: "Electric Guitar",
    pickups: "Burstbucker 1 & 2",
    price: 2499.0,
    color: "Tobacco Burst",
    stock: 10,
  },
  {
    id: 2,
    model: "SG Standard",
    type: "Electric Guitar",
    pickups: "490R & 490T",
    price: 1499.0,
    color: "Ebony",
    stock: 10,
  },
  {
    id: 3,
    model: "ES-335 Figured",
    type: "Electric Guitar",
    pickups: "MHS II Humbuckers",
    price: 3699.0,
    color: "Sixties Cherry",
    stock: 10,
  },
  {
    id: 4,
    model: "J-45 Standard",
    type: "Acoustic Guitar",
    body: "Round Shoulder Dreadnought",
    price: 2499.0,
    color: "Vintage Sunburst",
    stock: 10,
  },
  {
    id: 5,
    model: "Flying V",
    type: "Electric Guitar",
    pickups: "Dirty Fingers+ Humbuckers",
    price: 1899.0,
    color: "Ebony",
    stock: 10,
  },
];
